# Leave this out if using subdirectories in path. It causes issues with toCSS.
# baseURL: 'http://example.org/'
relativeURLs: true
languageCode: en
title: Connor Hensel
theme: hugo-devresume-theme
params:
  author: CowboySmall
  description: DevResume - Bootstrap 4 Resume/CV Template For Software Developers
  primaryColor: '#54B689'
  textPrimaryColor: '#292929'
  profile:
    enable: true
    name: Connor Hensel
    tagline: Front End Web Developer
    avatar: avatar.png
  contact:
    enable: true
    location: Alabama
    list:
      # - icon: fas fa-phone-square
        # url: 'tel:#'
        # text: 0123 4567 87
      - icon: fas fa-envelope-square
        url: 'mailto:#'
        text: chensel0603@nacc.edu
      - icon: fas fa-globe
        url: '#'
        text: www.yourwebsite.com
  skills:
    enable: true
    list:
      - title: Technical
        items:
          - details: JavaScript/Vue
          - details: Python
          - details: Node.js
          - details: Object-oriented design
          - details: Design websites
      - title: Strengths
        items:
          - details: Effective communication
          - details: Good under pressure
          - details: Strong problem solver
          - details: Good time management
  education:
    enable: true
    list:
      - degree: Highschool Diploma
        university: Cornerstone Christian Acedemy
        dates: 2019-2023
  awards:
    enable: false
    list:
      - name: Award Lorem Ipsum
        body: Microsoft lorem ipsum
        date: '2019'
      - name: Award Donec Sodales
        body: Oracle Aenean
        date: '2017'
  languages:
    enable: false
    list:
      - name: English
        level: Native
      - name: Spanish
        level: Professional
  interests:
    enable: true
    list:
      - name: Running
      - name: Guitar
      - name: 3d Art
      - name: Martial Arts
  summary:
    enable: true
    text: >-
      Summarise your career here. Donec quam felis, ultricies nec, pellentesque
      eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
      commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et
      magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis,
      ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et
      ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.
      Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis
      leo. Sed fringilla mauris sit amet nibh.
  experience:
    enable: true
    list:
      - title: JavaScript Self Taught
        dates: 2019 - Present
        company: Company Inc.
        details: >-
          Role description goes here ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
          sociis natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
          pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor
          sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget
          dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis
          parturient montes, nascetur ridiculus mus. Donec quam felis.
        items:
          - details: 'Lorem ipsum dolor sit amet, consectetuer.'
          - details: Aenean commodo ligula eget dolor.
          - details: Etiam ultricies nisi vel augue.
      - title: Python Self Taught
        dates: 2018-Present
        company: Company Inc.
        details: >-
          Role description goes here ipsum dolor sit amet, consectetuer
          adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
          sociis natoque penatibus et magnis dis parturient montes, nascetur
          ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
          pretium quis, sem. Donec pede justo, fringilla vel.
        items:
          - details: 'Lorem ipsum dolor sit amet, consectetuer.'
          - details: Aenean commodo ligula eget dolor.
  projects:
    enable: false
    list:
      - title: Project Lorem Ipsum
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Lorem ipsum dolor sit
          amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
          Aenean massa. Cum sociis natoque penatibus et magnis dis parturient
          montes, nascetur ridiculus mus.
      - title: Project Sed Fringilla
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
      - title: Project Praesent
        meta: Open Source
        tagline: >-
          You can use this section for your side projects. Cras dapibus. Vivamus
          elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo
          ligula, porttitor eu, consequat vitae, eleifend ac, enim.
  information:
    enable: false
    list:
      - title: Papers
        items:
          - details: 2018 · Lorem Ipsum
          - details: 2016 · Sed Fringilla
      - title: Interests
        details: 'Climbing, Snowboarding, Photography, Travelling'
  social:
    enable: true
    list:
      - icon: fab fa-github-square
        url: //github.com/ConnorHensel
        title: ConnorHensel
      # - icon: fab fa-linkedin
        # url: //linkedin.com/in/username
        # title: username
      # - icon: fab fa-twitter-square
        # url: //twitter.com/username
        # title: 'Connor Hensel'
  footer:
    copyright: Connor Hensel 2020
